INSERT INTO equipos (nombre, logo_url)
VALUES 
('Equipo A1', 'https://miweb.com/logos/equipoA1.png'),
('Equipo A2', 'https://miweb.com/logos/equipoA2.png'),
('Equipo A3', 'https://miweb.com/logos/equipoA3.png'),
('Equipo A4', 'https://miweb.com/logos/equipoA4.png'),
('Equipo B1', 'https://miweb.com/logos/equipoB1.png'),
('Equipo B2', 'https://miweb.com/logos/equipoB2.png'),
('Equipo B3', 'https://miweb.com/logos/equipoB3.png'),
('Equipo B4', 'https://miweb.com/logos/equipoB4.png'),
('Equipo C1', 'https://miweb.com/logos/equipoC1.png'),
('Equipo C2', 'https://miweb.com/logos/equipoC2.png'),
('Equipo C3', 'https://miweb.com/logos/equipoC3.png'),
('Equipo C4', 'https://miweb.com/logos/equipoC4.png'),
('Equipo D1', 'https://miweb.com/logos/equipoD1.png'),
('Equipo D2', 'https://miweb.com/logos/equipoD2.png'),
('Equipo D3', 'https://miweb.com/logos/equipoD3.png'),
('Equipo D4', 'https://miweb.com/logos/equipoD4.png'),
('Equipo E1', 'https://miweb.com/logos/equipoE1.png'),
('Equipo E2', 'https://miweb.com/logos/equipoE2.png'),
('Equipo E3', 'https://miweb.com/logos/equipoE3.png'),
('Equipo E4', 'https://miweb.com/logos/equipoE4.png'),
('Equipo F1', 'https://miweb.com/logos/equipoF1.png'),
('Equipo F2', 'https://miweb.com/logos/equipoF2.png'),
('Equipo F3', 'https://miweb.com/logos/equipoF3.png'),
('Equipo F4', 'https://miweb.com/logos/equipoF4.png');
